FROM ruby:3-slim-bookworm

RUN apt update

RUN apt-get install -y --no-install-recommends \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY entry.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entry.sh

EXPOSE 4000

WORKDIR /site

ENTRYPOINT [ "entry.sh" ]

CMD [ "bundle","exec","jekyll","serve", "-H", "0.0.0.0", "-P", "4000" ]