FROM ruby:3-slim-bookworm as base

RUN apt update

RUN apt-get install -y --no-install-recommends \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY Gemfile .
RUN bundle install
RUN rm Gemfile

FROM base

WORKDIR /site

CMD ["bundle", "exec", "jekyll","--help"]