name: Push to DockerHub

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "**/Dockerfile"
      - "**/entry.sh"
      - ".github/**/*"

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: jekyll-base
          tags: jekyll-base:latest
          outputs: type=docker,dest=/tmp/jekyll-base.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: jekyll-base
          path: /tmp/jekyll-base.tar
        
  build-jekyll-cli:
    runs-on: ubuntu-latest
    needs: build-base
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: jekyll-base
          path: /tmp
      -
        name: Load Docker image
        run: |
          docker load --input /tmp/jekyll-base.tar
          docker image ls -a
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOEKN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: jekyll-cli
          push: true
          tags: |
            sievelau/jekyll-cli:latest
          pull: false
  build-jekyll-server:
    runs-on: ubuntu-latest
    needs: build-base
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: jekyll-base
          path: /tmp
      -
        name: Load Docker image
        run: |
          docker load --input /tmp/jekyll-base.tar
          docker image ls -a
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOEKN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: jekyll-server
          push: true
          tags: |
            sievelau/jekyll-server:latest
          pull: false