name: Push to DockerHub

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "Dockerfile.*"
      - "entry.sh"
      - ".github/**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: ./Dockerfile.cli
            tag: sievelau/jekyll:cli
          - dockerfile: ./Dockerfile.server
            tag: sievelau/jekyll:server
          - dockerfile: ./Dockerfile.fat
            tag: sievelau/jekyll:fat
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOEKN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.tag }}